fix GHA invocation of docker tag push script
kubeflow/model-registry pull request #30
Opened 2024-03-06 10:38 UTC by tarilabs

The goal of this PR is to fix 2 issues in the current GHA invocation:
- typo in the GHA branch for `BUILD_CONTEXT==tag` vs `==main`
- `VERSION` needed to be pass down to push the tagged layer (the layers and rolling tags are already pushed from the steps above, what needs to happen is GHA need to instruct the script to just-push the newly created tag)

## Description

## How Has This Been Tested?

## Merge criteria:

- [x] The commits and have meaningful messages; the author will squash them [after approval](https://github.com/opendatahub-io/opendatahub-community/blob/main/contributor-cheatsheet.md#:~:text=Usually%20this%20is%20done%20in%20last%20phase%20of%20a%20PR%20revision) or will ask to merge with squash.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

2024-03-06 10:48 UTC, lampajr requested changes
Thanks @tarilabs , noticed just a typo

2024-03-06 10:48 UTC, lampajr commented on .github/workflows/build-and-push-image.yml
> +          VERISON=latest ./scripts/build_deploy.sh
```suggestion
          VERSION=latest ./scripts/build_deploy.sh
```

2024-03-06 10:53 UTC, tarilabs commented
notified of failing DCO check here: https://kubeflow.slack.com/archives/C7REE0ETX/p1709722338099339

> DCO for GitHub suggestion being applied
> Hi, Just thought of headsup to the KF community leaders, it seems to me some GitHub configuration is needed for those commits coming as GitHub Review suggestions, as allegedly they are the ones failing some automated DCO check.
> Example: https://github.com/kubeflow/model-registry/pull/30#discussion_r1514249445
> Thank you, hope this helps

2024-03-07 16:19 UTC, dhirajsb commented
lgtm :+1:

2024-03-07 18:02 UTC, dhirajsb approved these changes

2024-03-07 19:30 UTC, rareddy commented
/lgtm

2024-03-07 19:31 UTC, merged