py: fix acces token parsing
kubeflow/model-registry pull request #341
Opened 2024-09-03 14:59 UTC by Al-Pragliola

## Description

fixes #340

After running `registry.get_registered_model("X")` without providing an user_token in ModelRegistry initialization, I got the following error:

```
File /opt/app-root/lib64/python3.9/site-packages/mr_openapi/configuration.py:357, in Configuration.auth_settings(self)

350 auth = {}
351 if self.access_token is not None:
352 auth["Bearer"] = {
353 "type": "bearer",
354 "in": "header",
355 "format": "JWT",
356 "key": "Authorization", -->
357 "value": "Bearer " + self.access_token, <- affected line
358 }
359 return auth

TypeError: can only concatenate str (not "bytes") to str
```

thanks to @isinyaaa , we figured out that there was a bug in the token parsing function in the client code and switched from reading it from "bytes mode" to "text mode"

## How Has This Been Tested?

Uploaded the wheel on the notebook and rerun.

## Merge criteria:
- All the commits have been [_signed-off_](https://github.com/kubeflow/community/tree/master/dco-signoff-hook#signing-off-commits)  (To pass the `DCO` check)

- [ ] The commits have meaningful messages; the author will squash them after approval or in case of manual merges will ask to merge with squash.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work.
- [ ] Code changes follow the [kubeflow contribution guidelines](https://www.kubeflow.org/docs/about/contributing/).

2024-09-03 15:36 UTC, tarilabs commented
nice catch, thanks @Al-Pragliola @isinyaaa ;

/lgtm

just before merging, can you comment on potential idea to create a non-regression testing for this?

It doesn't "have to be" in this PR, but I want to track it before we merge, thanks!

2024-09-03 16:14 UTC, Al-Pragliola commented
What I would I do is a test where there's no user_token defined when initializing the client (ModelRegistry), `KF_PIPELINES_SA_TOKEN_PATH` env var set to a tmp file path, where the content is a mocked token, register a new model and then trying `get_registered_model` to get it back

2024-09-04 13:40 UTC, tarilabs reviewed
Awesome to have a non-regression along with the fix, thank you so much @Al-Pragliola ! 🚀 

One small suggestion, below.

The fixture looks to me following same pattern/style than other fixtures, and looks good to me.

Any further comment @isinyaaa ?
/lgtm

2024-09-04 13:40 UTC, tarilabs commented on clients/python/tests/conftest.py
> +    token_file.close()
```suggestion
    with tempfile.NamedTemporaryFile(delete=False) as token_file:
        token_file.write(b"Token")
```

possibly more pythonic

2024-09-04 15:27 UTC, isinyaaa approved these changes
lgtm, just a nit inline :)

2024-09-04 15:27 UTC, isinyaaa commented on clients/python/tests/conftest.py
> +        os.environ["KF_PIPELINES_SA_TOKEN_PATH"] = old_token_path
we don't actually need this, the envvar will be preserved outside the tests.

2024-09-04 16:04 UTC, isinyaaa commented on clients/python/tests/regression_test.py
> +def test_get_model_without_user_token(setup_env_user_token, client):
I see here you're already using it. So the scope reduction is a better practice.

2024-09-04 16:05 UTC, isinyaaa requested changes
I had misunderstood your intent before, sorry for the noise.

2024-09-04 17:02 UTC, isinyaaa approved these changes
On a third look this seems fine :) -- thanks @tarilabs for the reference:
https://stackoverflow.com/questions/25660064/in-which-order-are-pytest-fixtures-executed/64471427#64471427:~:text=while%20discouraging%20from%20relying%20on%20another%20factors%20(like%20order%20in%20test%20function%20arguments)%3A

2024-09-05 06:20 UTC, tarilabs approved these changes
/lgtm
/approve

2024-09-05 06:20 UTC, tarilabs commented on clients/python/tests/conftest.py
> +def setup_env_user_token():
i.e. we rely on scope for fixture ordering, and not fn arg ordering in the actual test fn.

this fixture is to be consumed by the pytest fn as an argument, when the test wants to opt-in to the (mocked) token.
when that happens, this fixture here needs to be balled before the fixture producing the MR python client.
this is achieved by this fixture having wider scope

2024-09-05 06:21 UTC, merged