Set up staticcheck linter for BFF
kubeflow/model-registry pull request #378
Opened 2024-09-11 19:48 UTC by Griffin-Sullivan

## Description
Linting the BFF folder with staticcheck and adding a step to run the linter in the BFF GitHub Action.

## How Has This Been Tested?
Make sure the action passes and tests pass.

## Merge criteria:

- All the commits have been [_signed-off_](https://github.com/kubeflow/community/tree/master/dco-signoff-hook#signing-off-commits)  (To pass the `DCO` check)

- [x] The commits have meaningful messages; the author will squash them after approval or in case of manual merges will ask to merge with squash.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work.
- [x] Code changes follow the [kubeflow contribution guidelines](https://www.kubeflow.org/docs/about/contributing/).

If you have UI changes

- [ ] The developer has added tests or explained why testing cannot be added.
- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Verify that UI/UX changes conform the UX guidelines for Kubeflow.

2024-09-12 18:28 UTC, ederign requested changes
LGTM to me and thanks for the cleanup! Just want to double check that with Matteo!

2024-09-12 18:28 UTC, ederign commented on .github/workflows/ui-bff-build.yml
> +      - uses: dominikh/staticcheck-action@v1
@tarilabs is there a policy to add third part actions on kubeflow?

2024-09-16 11:20 UTC, lucferbux commented
/lgtm

2024-09-26 17:56 UTC, Griffin-Sullivan commented
I've decided to use a different linting tool for the BFF so I'm going to close this and open another.

2024-09-26 17:56 UTC, closed without merging