Add GitHub Action for building and pushing UI and BFF images
kubeflow/model-registry pull request #446
Opened 2024-10-01 18:10 UTC by Griffin-Sullivan

## Description
Added a GH Action for building and pushing the UI and BFF images. Reuses the build script for Model Registry server, and edits the Makefile a little bit to get everything working. I also turned off image builds for MR server when a PR is being made only for UI / BFF changes. I can remove that if we want to keep building them.

## How Has This Been Tested?
Going to test the PR as `on: pull_request` then if it passes will update the PR to run the action `on: push`.

## Merge criteria:

- All the commits have been [_signed-off_](https://github.com/kubeflow/community/tree/master/dco-signoff-hook#signing-off-commits)  (To pass the `DCO` check)

- [ ] The commits have meaningful messages; the author will squash them after approval or in case of manual merges will ask to merge with squash.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work.
- [ ] Code changes follow the [kubeflow contribution guidelines](https://www.kubeflow.org/docs/about/contributing/).

If you have UI changes

- [ ] The developer has added tests or explained why testing cannot be added.
- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Verify that UI/UX changes conform the UX guidelines for Kubeflow.

2024-10-01 18:44 UTC, Griffin-Sullivan commented
My user must not have access to the creds for the kubeflow docker so I'm assuming there's no way to test this without having the bot do it on push to main? @tarilabs any ideas how I can test?

2024-10-02 13:00 UTC, tarilabs requested changes
> My user must not have access to the creds for the kubeflow docker so I'm assuming there's no way to test this without having the bot do it on push to main? @tarilabs any ideas how I can test?

When I face similar situation @Griffin-Sullivan , I did setup `DOCKERHUB_USERNAME` etc in my GitHub repo (my fork) and updated `IMG_ORG` to point at my username in dockerhub.io

It also gives you an idea/survey of the changes we will need to apply midstream (kind request: please remind me/us when this PR will be synchronized midstream!)

2024-10-02 13:00 UTC, tarilabs commented on .github/workflows/build-and-push-ui-images.yml
> +  pull_request:
I appreciate in the PR description is mentioned this `on: pull_request` is only for testing, but I'd rather make a comment so to make sure we don't forget before merging 😅

2024-10-02 17:54 UTC, Griffin-Sullivan commented
You can see on https://github.com/Griffin-Sullivan/model-registry/actions/runs/11147635638/job/30982430523?pr=1 that the Action is passing when I push to my own quay repo. You can find them here: https://quay.io/user/gsulliva/?tab=repos

The reason the build-and-test-image action is failing is because I'm forcing the build script to run with `quay.io` so once that is removed when we are ready to merge it should pass fine.

2024-10-03 10:24 UTC, alexcreasy commented on .github/workflows/build-and-push-ui-images.yml
> +    environment: griffin-testing # TODO: REMOVE LINE BEFORE MERGING
Just an extra reminder this line is here :D

2024-10-03 10:24 UTC, alexcreasy commented on scripts/build_deploy.sh
> +IMG_REGISTRY="quay.io" # TODO: CHANGE TO EMPTY STRING BEFORE MERGE!!!
Another reminder :D

2024-10-03 10:25 UTC, alexcreasy commented
Looks good, I haven't completely groked the logic but the general tasks all look good!

2024-10-04 15:00 UTC, Griffin-Sullivan commented
Latest run is still passing on https://github.com/Griffin-Sullivan/model-registry/actions/runs/11162537114/job/31027401589?pr=1. If someone will review this I can remove all the TODOs :smile:

2024-10-05 09:58 UTC, tarilabs reviewed
I think it's worthy to remove the TODOs

/lgtm

2024-10-05 09:58 UTC, tarilabs commented on .github/workflows/build-and-push-ui-images.yml
> +          IMG: ${{ env.IMG_ORG }}/${{ env.IMG_UI_REPO }}
this `IMG` will need to be prefixed with `quay.io` for midstream, correct?

I'm thinking if we should just be explicit and introduce `docker.io/` prefix in all GHAs 🤔 
what is your team thought here?:

2024-10-08 12:54 UTC, ederign approved these changes

2024-10-08 12:55 UTC, ederign commented
@tarilabs we need you to merge this one!

2024-10-08 12:58 UTC, alexcreasy approved these changes
All looks good to me.

2024-10-08 12:59 UTC, alexcreasy commented
@tarilabs would you mind approving this, if you're happy with the changes? It's outside my or Eder's jurisdiction :)

2024-10-08 13:02 UTC, tarilabs approved these changes
- https://github.com/kubeflow/model-registry/pull/446#pullrequestreview-2349523222
- https://github.com/kubeflow/model-registry/pull/446#pullrequestreview-2354408068
- https://github.com/kubeflow/model-registry/pull/446#pullrequestreview-2354417148

/approve

2024-10-08 13:03 UTC, alexcreasy commented
thanks @tarilabs

2024-10-08 13:03 UTC, merged