[WIP] Apply PF Breaking Change Best Practices to MUI Theme Stylesheet
kubeflow/model-registry pull request #484
Opened 2024-10-16 20:43 UTC by jenny-s51

## Description

WIP: updates theming overrides to align with PF breaking change standards. Needs clarity from PF core for remaining overrides. 

## How Has This Been Tested?

N/A, CSS refactoring only. 

## Merge criteria:

- All the commits have been [_signed-off_](https://github.com/kubeflow/community/tree/master/dco-signoff-hook#signing-off-commits)  (To pass the `DCO` check)

- [ ] The commits have meaningful messages; the author will squash them after approval or in case of manual merges will ask to merge with squash.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work.
- [ ] Code changes follow the [kubeflow contribution guidelines](https://www.kubeflow.org/docs/about/contributing/).

If you have UI changes

- [ ] The developer has added tests or explained why testing cannot be added.
- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Verify that UI/UX changes conform the UX guidelines for Kubeflow.

2024-10-18 10:54 UTC, alexcreasy requested changes
Thanks for the contribution Jenny! I haven't tested this out yet, just read through the code, but it looks good. 

There are just a few tiny changes related to checking in Red Hat references to the community codebase to take care of.

I'll update this if I find anything during testing :)

2024-10-18 10:54 UTC, alexcreasy commented on clients/ui/frontend/src/style/MUI-theme.scss
> +  // TODO: https://issues.redhat.com/browse/RHOAIENG-14702,
Small nit, we shouldn't check Red Hat references into the community codebase, could you remove the link to the internal JIRA please? :)

2024-10-18 10:54 UTC, alexcreasy commented on clients/ui/frontend/src/style/MUI-theme.scss
> +  // TODO: https://issues.redhat.com/browse/RHOAIENG-14702
Likewise here

2024-10-18 14:18 UTC, jenny-s51 reviewed
Thank you for reviewing @alexcreasy - updated the stylesheet to apply your feedback.

2024-10-18 15:11 UTC, lucferbux commented
@jenny-s51 I was trying to spot which css is overriding the button corner radious, but running it i've spotted this issue:
<img width="1202" alt="Screenshot 2024-10-18 at 17 03 46" src="https://github.com/user-attachments/assets/3a41d2d1-27ac-4972-95d4-47dacca0f1c1">
I'm sorry i cannot add it in the right line 😅

2024-10-18 15:12 UTC, lucferbux commented on clients/ui/frontend/src/style/MUI-theme.scss
> +  // Needs clarity --pf-v6-c-menu-toggle--m-plain--BorderRadius does not exist
Ah, this is the right line, but it doesn't seem a new addition, regardless of that, a 50% would make that weird shape in the button

2024-10-18 21:16 UTC, jenny-s51 commented
Nice catch, thanks @lucferbux ! I've pushed a fix for the buttons and am still investigating as the modals will require some refactoring make sure the error message in the modal is themed correctly. `DashboardModalFooter` currently uses `Stack` and`ActionsList` around the buttons to render the Alert component like this:

<img width="488" alt="Screenshot 2024-10-18 at 5 03 01 PM" src="https://github.com/user-attachments/assets/fd91c1c9-3ff3-4b00-a087-6375d6cc0c18">

When using a form input in a modal like this, the PF recommendation is to render Alerts [at the top of the form](https://staging-v6.patternfly.org/components/forms/form#invalid-with-form-alert). Currently working on updating the modals to apply this change.

2024-10-24 18:21 UTC, jenny-s51 reviewed
Updated and refactored the modals to apply the correct styling. The action buttons now have the correct button corner radius and the alert is shown at the top of the modal per the PF design recommendations cc @lucferbux 

<img width="586" alt="Screenshot 2024-10-24 at 1 27 23 PM" src="https://github.com/user-attachments/assets/31af3f2a-d504-4c05-ae5f-298e5e57aca6">

2024-10-28 10:23 UTC, lucferbux approved these changes
/lgtm

So far breaking down some components into constants is a really great pattern, we are breaking a little bit the 1:1 match with downstream but checking the latest changes is not that big of a deal and would benefit in the future.

@ederign @alexcreasy could you guys take a look and approve?

2024-10-28 12:05 UTC, ederign approved these changes

2024-10-28 12:06 UTC, ederign commented
/lgtm

2024-10-28 12:07 UTC, merged