Add enum and env var to conditionally render MUI theme
kubeflow/model-registry pull request #564
Opened 2024-11-15 15:53 UTC by jenny-s51

## Description

Adds env var to support toggling MUI theme on / off. 
<img width="1491" alt="Screenshot 2024-11-15 at 10 51 56 AM" src="https://github.com/user-attachments/assets/1aa823e1-2457-49b9-8ff7-e54e8da70d5a">
<img width="1486" alt="Screenshot 2024-11-15 at 10 52 52 AM" src="https://github.com/user-attachments/assets/73f2fd8e-149a-4a34-9ca6-03c022dd7fb5">

## How Has This Been Tested?

Verify that the MUI theme is toggled on / off based on the value of `STYLE_THEME`. 

Tests N/A, visual updates only. 

## Merge criteria:

- All the commits have been [_signed-off_](https://github.com/kubeflow/community/tree/master/dco-signoff-hook#signing-off-commits)  (To pass the `DCO` check)

- [x] The commits have meaningful messages; the author will squash them after approval or in case of manual merges will ask to merge with squash.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work.
- [x] Code changes follow the [kubeflow contribution guidelines](https://www.kubeflow.org/docs/about/contributing/).

If you have UI changes

- [x] The developer has added tests or explained why testing cannot be added.
- [x] Included any necessary screenshots or gifs if it was a UI change.
- [x] Verify that UI/UX changes conform the UX guidelines for Kubeflow.

2024-11-18 14:45 UTC, Griffin-Sullivan commented on clients/ui/frontend/src/app/pages/modelRegistry/screens/ModelPropertiesTableRow.tsx
> +  }, []);
Since this gets reused a lot I would guess a custom hook like `useMUI` would be a good idea

2024-11-18 18:28 UTC, lucferbux requested changes
Ok changes look reaaly great, but overall, we would wanna avoid this global declarations, apologies for not detailing too much in the description the conditional rendering, but the main goal for this is just to turn it on or off at **build** time, for that:

* Instead of having a global window value, let's just control this with a constant
* That constant could be either a boolean, but I would suggest moving this into an ENUM and then have some utility to control (we only want MUI but it's a good practice to get extensibility)
* We might not want a switcher in the UI, upstream should stick with MUI, this is just for us to be able to contribute both upstream with MUI and downstream with regular PF6 look and feel
* The global const should be an env variable, I'm working right now on a PR to enhance our env variable handling but so far it's gonna be similar on [what we have in odh](https://github.com/opendatahub-io/odh-dashboard/blob/main/frontend/src/utilities/const.ts#L20), so you can follow that pattern in the `const.ts` file
* Since we don't have proper env support (I'm working on it right now) you can test that in a similar way as we have [here](https://github.com/kubeflow/model-registry/blob/main/clients/ui/frontend/package.json#L30) just add the env variable you decided to use (maybe STYLE_THEME) to the Kubeflow value (if it's a boolean call it other way) and add that to the dev command, I can tweak it later in my PR

2024-11-18 22:09 UTC, jenny-s51 reviewed
Thank you @Griffin-Sullivan @lucferbux for your feedback - updated the PR to reflect your comments.

2024-11-20 17:45 UTC, lucferbux requested changes
Ok, just a couple of nits, everything else working as expected!

2024-11-20 17:45 UTC, lucferbux commented on clients/ui/frontend/src/app/App.tsx
> +    isSwitched?: boolean;
Do we still need `isSwitched`?

2024-11-21 15:22 UTC, jenny-s51 commented on clients/ui/frontend/src/app/pages/modelRegistry/screens/ModelVersions/ModelVersionListView.tsx
> +                  {STYLE_THEME === Theme.MUI ? (
Great idea, thanks! Updated

2024-11-21 17:26 UTC, lucferbux approved these changes
/lgtm

2024-11-21 19:27 UTC, ederign approved these changes

2024-11-21 19:28 UTC, ederign commented
/label approved

2024-11-21 19:28 UTC, merged